version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18 # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490

  # test core
  pre_build:
    on-failure: ABORT
    commands:
      - cd abe-gql-core
      - NODE_ENV=dev npm ci
      - npm run test:format
      - npm run test:license
      - npm run test:lint
      - npm run test:types
      # - npm run test:audit
      - npm run test
      - cd ..

  build:
    commands:
      - cd aws-deployment
      - NODE_ENV=dev npm ci
      # this is just to compile ts; serverless will run its own build at deploy
      - npm run build

artifacts:
  files:
    - "**/*"
  enable-symlinks: yes
