name: Azure CD

on:
  push:
    branches:
      - azure-cicd
defaults:
  run:
    shell: bash
    working-directory: azure-deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "18.13"
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          func azure functionapp publish dev-abe-fa-mongo --typescript --env dev
