name: Azure CD

on:
  push:
    branches:
      - azure-cicd
defaults:
  run:
    shell: bash
    working-directory: azure-deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "18.13"

    - name: Log in to Azure
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        echo "$AZURE_CREDENTIALS" > azure_credentials.json
        az login --service-principal -u $(jq -r .clientId azure_credentials.json) -p $(jq -r .clientSecret azure_credentials.json) --tenant $(jq -r .tenantId azure_credentials.json)

    - name: Deploy Azure Function App
      run: |
        make deploy